apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-nobvik
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-nobvik
    app.kubernetes.io/part-of: jvm-build-suite-application-fxet
  name: jvm-build-suite-component-nobvik
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-nobvik
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-nobvik
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-afip-tenant/jvm-build-suite-application-fxet/jvm-build-suite-component-nobvik@sha256:b2ac1001302da9eecec7f4915e55805eee484f9bc80f6df535eaaca615e6fa87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
